version: '3.4'

services:

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: src/ApiGateways/MsSystem.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  identity:
    container_name: identity
    build:
      context: .
      dockerfile: src/Services/Identity/MsSystem.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  oaapi:
    container_name: oaapi
    build:
      context: .
      dockerfile: src/Services/OA/MsSystem.OA.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sysapi:
    container_name: sysapi
    build:
      context: .
      dockerfile: src/Services/System/MsSystem.Sys.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  wfapi:
    container_name: wfapi
    build:
      context: .
      dockerfile: src/Services/WorkFlow/MsSystem.WF.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    container_name: web
    build:
      context: .
      dockerfile: src/Web/MVC/MsSystem.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
