version: '3.4'

services:

  gateway:
    build:
      context: .
      dockerfile: src/ApiGateways/MsSystem.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 
  identity:
    build:
      context: .
      dockerfile: src/Services/Identity/MsSystem.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 
  sysapi:
    build:
      context: .
      dockerfile: src/Services/System/MsSystem.Sys.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  weixinapi:
    build:
      context: .
      dockerfile: src/Services/Weixin/MsSystem.Weixin.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  wfapi:
    build:
      context: .
      dockerfile: src/Services/WorkFlow/MsSystem.WF.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  oaapi:
    build:
      context: .
      dockerfile: src/Services/OA/MsSystem.OA.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

